--------------------------------------------------------
--  Fichier créé - samedi-février-01-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLASSE
--------------------------------------------------------

  CREATE TABLE "ROOT"."CLASSE" OF "ROOT"."CLASSE_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOI
--------------------------------------------------------

  CREATE TABLE "ROOT"."EMPLOI" OF "ROOT"."EMPLOI_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENSEIGNANT
--------------------------------------------------------

  CREATE TABLE "ROOT"."ENSEIGNANT" OF "ROOT"."ENSEIGNANT_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ETUDIANT
--------------------------------------------------------

  CREATE TABLE "ROOT"."ETUDIANT" OF "ROOT"."ETUDIANT_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MATIERE
--------------------------------------------------------

  CREATE TABLE "ROOT"."MATIERE" 
   (	"IDMATIERE" NUMBER(*,0), 
	"LIBELLE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALLE
--------------------------------------------------------

  CREATE TABLE "ROOT"."SALLE" OF "ROOT"."SALLE_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "ROOT"."TEST" 
   (	"ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ROOT.CLASSE
SET DEFINE OFF;
Insert into ROOT.CLASSE (IDCLASSE,LIBELLE) values ('2',ROOT.LIBELLECLASSE_T('im','im',3,'1'));
Insert into ROOT.CLASSE (IDCLASSE,LIBELLE) values ('1',ROOT.LIBELLECLASSE_T('ing','ing',2,'2'));
REM INSERTING into ROOT.EMPLOI
SET DEFINE OFF;
Insert into ROOT.EMPLOI (DATEDEB,DATEFIN,MATRICULEENSEIGNANT,IDCLASSE,IDMATIERE,IDSALLE) values (ROOT.DATE_T('lundi',12,12,2013,30,8),ROOT.DATE_T('lundi',12,12,2013,0,10),'1','1','1','1');
Insert into ROOT.EMPLOI (DATEDEB,DATEFIN,MATRICULEENSEIGNANT,IDCLASSE,IDMATIERE,IDSALLE) values (ROOT.DATE_T('mardi',13,12,2013,30,8),ROOT.DATE_T('lundi',12,12,2013,0,10),'1','2','2','1');
REM INSERTING into ROOT.ENSEIGNANT
SET DEFINE OFF;
Insert into ROOT.ENSEIGNANT (IDPERSONNE,NOM,PRENOM,ADRESSE,MATRICULEENSEIGNANT,DEPARTEMENT,TITRE) values ('1','linus','trvld',ROOT.ADRESSE_T(12,'15','paris','france'),'1','informatique','A');
Insert into ROOT.ENSEIGNANT (IDPERSONNE,NOM,PRENOM,ADRESSE,MATRICULEENSEIGNANT,DEPARTEMENT,TITRE) values ('2','larry','page',ROOT.ADRESSE_T(12,'16','paris','france'),'3','informatique','A');
REM INSERTING into ROOT.ETUDIANT
SET DEFINE OFF;
Insert into ROOT.ETUDIANT (IDPERSONNE,NOM,PRENOM,ADRESSE,NCE,IDCLASSE) values ('3','steve','woz',ROOT.ADRESSE_T(12,'18','paris','france'),'3','1');
Insert into ROOT.ETUDIANT (IDPERSONNE,NOM,PRENOM,ADRESSE,NCE,IDCLASSE) values ('4','richard','stm',ROOT.ADRESSE_T(12,'20','paris','france'),'6','1');
REM INSERTING into ROOT.MATIERE
SET DEFINE OFF;
Insert into ROOT.MATIERE (IDMATIERE,LIBELLE) values ('1','math');
Insert into ROOT.MATIERE (IDMATIERE,LIBELLE) values ('2','BD');
REM INSERTING into ROOT.SALLE
SET DEFINE OFF;
Insert into ROOT.SALLE (IDSALLE,LIBELLE,NUMSALLE) values ('3','C','12');
Insert into ROOT.SALLE (IDSALLE,LIBELLE,NUMSALLE) values ('1','labo','22');
Insert into ROOT.SALLE (IDSALLE,LIBELLE,NUMSALLE) values ('2','labo','23');
REM INSERTING into ROOT.TEST
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table EMPLOI
--------------------------------------------------------

  ALTER TABLE "ROOT"."EMPLOI" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "ROOT"."TEST" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ROOT"."TEST" ADD CONSTRAINT "TEST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENSEIGNANT
--------------------------------------------------------

  ALTER TABLE "ROOT"."ENSEIGNANT" ADD CONSTRAINT "ENSEIGNANT_CON" UNIQUE ("IDPERSONNE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ROOT"."ENSEIGNANT" ADD PRIMARY KEY ("MATRICULEENSEIGNANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ROOT"."ENSEIGNANT" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ETUDIANT
--------------------------------------------------------

  ALTER TABLE "ROOT"."ETUDIANT" ADD CONSTRAINT "ETUDIANT_ID_CON" UNIQUE ("IDPERSONNE", "NCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ROOT"."ETUDIANT" ADD PRIMARY KEY ("NCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ROOT"."ETUDIANT" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALLE
--------------------------------------------------------

  ALTER TABLE "ROOT"."SALLE" ADD PRIMARY KEY ("IDSALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ROOT"."SALLE" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLASSE
--------------------------------------------------------

  ALTER TABLE "ROOT"."CLASSE" ADD PRIMARY KEY ("IDCLASSE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ROOT"."CLASSE" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MATIERE
--------------------------------------------------------

  ALTER TABLE "ROOT"."MATIERE" ADD PRIMARY KEY ("IDMATIERE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOI
--------------------------------------------------------

  ALTER TABLE "ROOT"."EMPLOI" ADD FOREIGN KEY ("IDCLASSE")
	  REFERENCES "ROOT"."CLASSE" ("IDCLASSE") ENABLE;
 
  ALTER TABLE "ROOT"."EMPLOI" ADD FOREIGN KEY ("MATRICULEENSEIGNANT")
	  REFERENCES "ROOT"."ENSEIGNANT" ("MATRICULEENSEIGNANT") ENABLE;
 
  ALTER TABLE "ROOT"."EMPLOI" ADD FOREIGN KEY ("IDMATIERE")
	  REFERENCES "ROOT"."MATIERE" ("IDMATIERE") ENABLE;
 
  ALTER TABLE "ROOT"."EMPLOI" ADD FOREIGN KEY ("IDSALLE")
	  REFERENCES "ROOT"."SALLE" ("IDSALLE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ETUDIANT
--------------------------------------------------------

  ALTER TABLE "ROOT"."ETUDIANT" ADD FOREIGN KEY ("IDCLASSE")
	  REFERENCES "ROOT"."CLASSE" ("IDCLASSE") ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_TEST
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."BI_TEST" 
  before insert on "TEST"               
  for each row  
begin   
    select "TEST_SEQ".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER "ROOT"."BI_TEST" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLASSE_T1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."CLASSE_T1" 
BEFORE
insert on "CLASSE"
for each row
begin
select "CLASSE_SEQ".nextval into :NEW.IDCLASSE from dual;
end;
/
ALTER TRIGGER "ROOT"."CLASSE_T1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ENSEIGNANT_T1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."ENSEIGNANT_T1" 
BEFORE
insert on "ENSEIGNANT"
for each row
begin
select "ENSEIGNANT_SEQ".nextval into :NEW.MATRICULEENSEIGNANT from dual; 

end;
/
ALTER TRIGGER "ROOT"."ENSEIGNANT_T1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ETUDIANT_T1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."ETUDIANT_T1" 
BEFORE
insert on "ETUDIANT"
for each row
begin
select "ETUDIANT_SEQ".nextval into :NEW.NCE from dual;
end;
/
ALTER TRIGGER "ROOT"."ETUDIANT_T1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MATIERE_T1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."MATIERE_T1" 
BEFORE
insert on "MATIERE"
for each row
begin
 select "MATIERE_SEQ".nextval into :NEW.IDMATIERE from dual; 
end;
/
ALTER TRIGGER "ROOT"."MATIERE_T1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SALLE_T1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."SALLE_T1" 
BEFORE
insert on "SALLE"
for each row
begin
select "SALLE_SEQ".nextval into :NEW.IDSALLE from dual;
end;
/
ALTER TRIGGER "ROOT"."SALLE_T1" ENABLE;
